// Automatically generated by astro-icon
// 2972f83d73973b7617b954fab282b6ebc13605b69599d5bd9247454be1ab345f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-left"
		| "arrow-nav-bar"
		| "arrow-nav-bar-back"
		| "arrow-right"
		| "henk-logo"
		| "icon-arrow-down"
		| "icon-arrow-left"
		| "icon-arrow-left-nav-back"
		| "icon-arrow-right"
		| "icon-arrow-right-animated"
		| "icon-arrow-right-nav-next"
		| "icon-calendar"
		| "icon-calendar-2"
		| "icon-cart"
		| "icon-cart-feather"
		| "icon-chevron-down"
		| "icon-chevron-up"
		| "icon-close"
		| "icon-hamburger"
		| "icon-location"
		| "icon-phone"
		| "icon-search"
		| "icon-trashcan"
		| "icon-truck"
		| "logo-henk-solo";
}